#!/bin/bash

BASHWF="${HOME}/bashwf"

source "$BASHWF/config"

# If we are not in our home directory cd to it.
if [[ "$(pwd)" != "${HOME}" ]]; then
    cd "${HOME}"
fi

color_prompt=no

case "$TERM" in
    cygwin) color_prompt=yes;;
    xterm-color) color_prompt=yes;;
esac

if [[ $TERM == "linux" ]]; then
    UNICODE_WORKFLOW="FALSE"
fi

if [[ -n $FORCE_COLOR_WORKFLOW && $FORCE_COLOR_WORKFLOW == "TRUE" ]]; then
    color_prompt=yes
    unset FORCE_COLOR_WORKFLOW;
fi

function command_exists()
{
    hash "$1" 2>/dev/null
    return $?
}

function try_source_path()
{
    RELPATH="$1"
    EXTENSION="$2"

    MODULE_PATH="$BASHWF/${RELPATH}"

    # Load our bashrc modules if they exist
    if [[ -d "$MODULE_PATH" ]]; then

        for MODULE in $MODULE_PATH/*.$EXTENSION
        do
            MODULE_NAME=${MODULE##*/}
            MODULE_NAME=${MODULE_NAME%.*}
            echo -n "$MODULE_NAME: "
            source $MODULE
        done

    fi
}

echo ""
echo "Loading Bash Modules"
try_source_path "bashrc" "bashrc"

echo ""
echo "Loading Bash Functions"
try_source_path "functions" "func"

echo ""

unset color_prompt;

# Let the new shell use our PATH
export PATH