#!/bin/bash

if [[ -n $BASHWF ]]; then
  # Bash Workflow has already been setup. This might be a subshell.
  SUBWF="$BASHWF"
else
  BASHWF="${HOME}/bashwf"
fi

source "${BASHWF}/config"
source "${BASHWF}/utils.func"
source "${BASHWF}/init_unicode.sh"
source "${BASHWF}/init_colors.sh"

if [[ -z $SUBWF ]]; then
  # Bash Workflow has already been setup. This might be a subshell. 
  source "${BASHWF}/init.sh"
fi

# Let the new shell use our PATH
export PATH

# Bash Workflow is now setup.
export BASHWF