#!/bin/bash

if [[ -n $BASHWF ]]; then
  # Bash Workflow has already been setup. This might be a subshell.
  SUBWF="$BASHWF"
  BASHWF_SYS="$SUBWF/system"
  BASHWF_USER="$SUBWF/user"
else
  BASHWF="${HOME}/bashwf"
  BASHWF_SYS="$BASHWF/system"
  BASHWF_USER="$BASHWF/user"
fi

source "${BASHWF_SYS}/sys_init.sh"

if [[ -z $SUBWF ]]; then
  # Bash Workflow has already been setup. This might be a subshell.
  source "${BASHWF_SYS}/init.sh"
fi

source "${BASHWF_SYS}/export.sh"